language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pep8
  - pip install coveralls
before_script:
  - "pep8 --exclude=libs,static --ignore=W191,E128,E501 ."
script:
  - ./manage.py test activities health
  - coverage run --source=activities,health manage.py test activities health
after_success: coveralls
sudo: false
# whitelist
branches:
  only:
    - master
